# Generated by Django 3.1.1 on 2021-05-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('message_type', models.CharField(max_length=200)),
                ('status', models.CharField(default='OK', max_length=200)),
            ],
        ),
    ]
