# Generated by Django 3.1.1 on 2021-05-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_admin'),
        ('properties', '0002_property_user'),
        ('communications', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='received_by_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
