# Generated by Django 3.1.1 on 2021-04-29 00:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='user',
            name='last_session',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 0, 7, 5, 670760)),
        ),
    ]
