# Generated by Django 3.1.1 on 2021-04-29 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210429_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_session',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 0, 11, 39, 774427)),
        ),
    ]
