# Generated by Django 3.1.1 on 2021-04-29 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210429_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_session',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
