# Generated by Django 3.1.1 on 2021-05-12 23:11

from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import User

def add_user(apps, schema_editor):
    User.objects.create(first_name='admin', last_name='admin')

def delete_user(apps, schema_editor):
    User.objects.get(email='admin@admin.cl').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210429_0039'),
    ]

    operations = [migrations.RunPython(add_user),
    ]
