# Generated by Django 3.1.1 on 2021-05-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('water', models.BooleanField(default=0)),
                ('electricity', models.BooleanField(default=0)),
                ('sewer', models.BooleanField(default=0)),
            ],
        ),
    ]
