# Generated by Django 3.1.1 on 2021-05-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.TextField(default='santiago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='contact',
            field=models.CharField(default='ramiro', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='Title population', max_length=200),
            preserve_default=False,
        ),
    ]
