# Generated by Django 3.1.1 on 2021-06-12 22:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20210530_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), default=[[1, 1]], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='photos_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
