# Generated by Django 3.1.1 on 2021-06-13 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210613_0030'),
        ('properties', '0004_auto_20210612_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='commune',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.commune'),
            preserve_default=False,
        ),
    ]
